config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'

  resources :investments, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :offered_services, only: [:index, :show, :new, :create]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :groups, only: [:show, :new, :create, :edit, :update, :destroy] do
    member do
      post "set_favori/:investment_id", to: 'groups#set_favori', as: :set_favori
    end
    resources :users_groups, only: [:index, :show] do
      collection do
        post :join_request
        post :invite
      end
    end
  end

  resources :users_groups, only: [] do
    member do
      patch :confirm
    end
  end

end

app/models/investment.rb
class Investment < ApplicationRecord
  has_many :groups
  # has_one :group, foreign_key: :selected_investment_id
  belongs_to :user
  has_many :offered_services, dependent: :destroy

  has_one_attached :photo

  validates :investment_name, presence: true, uniqueness: true
  validates :punchline, presence: true
  validates :winemaker_name, presence: true
  validates :domaine_name, presence: true
  validates :description, presence: true
  validates :region, presence: true, inclusion: { in: ["Alsace", "Beaujolais", "Bordeaux", "Bourgogne", "Champagne", "Corse", "Jura", "Languedoc-Roussillon", "Provence", "Savoie", "Sud-Ouest", "Vallée de la Loire", "Vallée du Rhône"] }, allow_nil: true
  validates :designation, presence: true
  validates :ticket_amount, presence: true
  validates :investment_total, presence: true
  validates :share_available, presence: true
  validates :total_share, presence: true
  validates :remuneration, presence: true
  validates :winemaker_profile, presence: true, inclusion: { in: ["Jeune vigneron", "Vigneron installé"] }, allow_nil: true

  attr_accessor :match

  def completion_percentage_for(group)
    100 * (group.members.size * ticket_amount.to_f) / investment_total
  end
end

app/controllers/investments_controller.rb
class InvestmentsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :show]

  def index
    @group = params.key?(:group) ? Group.new(group_params_search) : Group.new
    @investments = InvestmentsByGroup.call(@group)
  end

  def new
    @investment = Investment.new
  end

  def create
    @investment = Investment.new(investments_strong_params)
    @investment.user = current_user
    if @investment.save
      redirect_to investment_path(@investment)
    else
      render 'new'
    end

  end

  def show
     @investment = Investment.find(params[:id])
  end

  def destroy
    @investment = Investment.find(params[:id])
    @investment.destroy!

  end

  def edit
    @investment = Investment.find(params[:id])
  end

  def update
    @investment = Investment.find(params[:id])
    @investment.update!(investment_params)

    redirect_to investmenet_path(@investment)
  end

private

  def investments_strong_params
    params.require(:investment).permit(
      :investment_name, :punchline, :winemaker_name, :domaine_name, :description,
      :bio, :region, :designation, :ticket_amount, :investment_total, :share_available,
      :total_share, :profitability, :remuneration, :winemaker_profile,
      :deferred_remuneration, :date_of_end, :photo
    )
  end


  def group_params_search
    params.require(:group).permit(
      :region,
      :ticket_amount,
      :investment_total,
      :share_available,
      :services,
      :winemaker_profile,
      :deferred_remunation
    )
  end
end

app/views/investments/_cards_results.html.erb
<div class="cards-result">
  <% investments.each do |investment| %>
        <div class="card-result2">
    <div class="card-header">
      <div class="image-carte">
        <%= cl_image_tag investment.photo.key, height: 200, width: 300, crop: :fill if investment.photo.attached? %>
      </div>
      <div class="infos-text">
          <div class="region-name">
            <%= investment.region %>
          </div>
          <div class="designation">
            <%= investment.designation %>
          </div>
          <hr>
          <div class="domaine-name">
            <%= investment.domaine_name %>
          </div>
          <div class="producteur">
            Chouchouté par <%= investment.user.first_name %> <%= investment.user.last_name %>
          </div>
          <hr>
          <div class="match_chiffre">
          <%= investment.match %> % de matching
          </div>
      </div>
      <div class="matching">
        <svg viewBox="0 0 161 301" class="drinks" style="height: 100px" data-size="<%= investment.match / 100.0 %>">
        <clipPath id="wine-clippath">
        <path d="M80.125,138.75c-5.973,0 -12.822,-1.152 -19.834,-3.387l-0.166,-0.053c-6.667,-2.123 -13.482,-5.221 -19.849,-9.235l-0.151,-0.095c-16.52,-10.43 -30,-26.96 -30,-48.48c0,-12.61 7.5,-38.75 16.47,-56.25l106.64,0c9.01,17.75 16.89,43.64 16.89,56.25c0,38.585 -44.017,61.162 -69.848,61.25l-0.152,0Z" fill="#000"></path>
        </clipPath>
        <image xlink:href="https://s3-us-west-2.amazonaws.com/s.cdpn.io/395186/wine.svg" x="0" y="0" width="100%" height="100%"></image>
        <g class="glass-fill" clip-path="url(#wine-clippath)">
          <rect x="10" y="20" width="31" height="120" style="fill: #874640;"></rect>
          <rect x="40" y="20" width="21" height="120" style="fill: #AA6F65;"></rect>
          <rect x="60" y="20" width="21" height="120" style="fill: #874640;"></rect>
          <rect x="80" y="20" width="70" height="120" style="fill: #751D19;"></rect>
        </g>
          </svg>
      </div>
  </div>
  <div class="card-footer">
    <div class="price">
      Ticket d'entrée <strong><%= number_to_currency(investment.ticket_amount, precision: 0, :unit => " € ", format: "%n %u") %></strong>
    </div>
    <div class="nb-parts">
      <%= investment.share_available %> parts
    </div>
    <a><%= link_to "Plus d'infos", investment_path(investment), class: 'btn-bot-green' %></a>
  </div>
</div>
  <% end %>
</div>

app/views/investments/_show_groups.html.erb
<% investment.groups.each do |group|  %>
  <% i_total      = investment.investment_total %>
  <% i_collect    = investment.ticket_amount * group.members.size%>
  <% ticket       = investment.ticket_amount %>
  <% users_group  = current_user.users_groups.find_by(group: group) %>

  <div class="d-flex justify-content-between align-items-center ">

    <div class="group-name align-items-center">
      <div class="d-flex align-items-center" >
        <div class="align-self-center">
          <p><%= image_tag group.image_url, class: "avatar-bordered", alt: "avatar-bordered" %></p>
        </div>
        <div class="align-self-center pl-3 ">
          <p> <small> <%= group.name %> </small> </p>
        </div>
      </div>
    </div>


      <div class="progressbar align-items-center">
        <div class="d-flex align-items-center pr-3 ">
          <h4 class="text-center" style="color:#86B04A"><strong><%= number_to_currency(group.members.size * investment.ticket_amount, precision: 0, :unit => "€", format: "%n %u") %></strong></h4>
          <p><small class="pl-2 ">collectés</small></p>
        </div>

        <div class=" d-flex progress-bar bg-info" role="progressbar" style="width: <%= investment.completion_percentage_for(group) * 1.3 %>%" aria-valuenow="<%=investment.completion_percentage_for(group)%>" aria-valuemin="0" aria-valuemax="100"> <small> <strong><%=investment.completion_percentage_for(group).round%></strong> %</small>


        </div>
      </div>


    <div class="ticket-demandes align-items-center text-center pr-1">
      <p><strong> <h4 style="color:#86B04A"><%= (((i_total) - (i_collect)) / (ticket)) %></strong></h4><small>parts restantes</small> </p>
    </div>

      <% if group.admin == current_user %>
         <p style="color:#a23e48" class="demandes"><small><i>Vous êtes admin</i></small></p>
      <% elsif users_group.nil? %>
        <p class="request-button ">
          <%= link_to "Rejoindre", join_request_group_users_groups_path(group), method: :post, class: 'btn-invest-first btn-invest-test', remote: true %>
        </p>
      <% elsif users_group.status == "waiting" %>
        <p style="color:#a23e48" class="demandes"><small><i>Vous avez déjà été invité sur ce groupe</i></small></p>
      <% elsif users_group.status == "pending" %>
         <p style="color:#a23e48" class="demandes"><small><i>Votre demande est en cours</i></small></p>
      <% elsif users_group.status == "validate" %>
        <p style="color:#a23e48" class="demandes"><small><i>Vous êtes déjà membre</i></small></p>
      <% end %>
    </div>
    <% if group.ready? %>
    <div class="container-button-green">
      <%= link_to "Envoyer une demande d'investissement au vigneron", "#", class: 'btn btn-top-green', id:'sweet-alert-demo', remote: true %>
    </div>

  <% end %>
    <hr>
<% end %>

app/views/investments/create.html.erb
<h1>Investments#create</h1>
<p>Find me in app/views/investments/create.html.erb</p>





<h1 class='title-page'>Publier un nouvel investissement</h1>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <%= simple_form_for @investment do |f| %>
        <%= f.input :investment_name, label: 'Nom investissemernt' %>
        <%= f.input :punchline, label: 'puncline de l\'invest' %>
        <%= f.input :winemaker_name, label: 'your name' %>
        <%= f.input :region, label: 'region' %>
        <%= f.input :domaine_name, label: 'nom de votre deomaine' %>
        <%= f.input :description, label: 'votre description'%>
        <%= f.input :bio, label: 'oui / non'%>
        <%= f.input :designation, label: 'Appelation' %>
        <%= f.input :ticket_amount, label: 'Montant du ticket' %>
        <%= f.input :investment_total,label: 'Montant du ticket' %>
        <%= f.input :share_available, label: 'Tarif à la journée'%>
        <%= f.input :total_share, label: 'parts totales'  %>
        <%= f.input :profitability, label: '% rendement' %>
        <%= f.input :remuneration, label: 'nbr de bouteilles' as: :file %>
        <%= f.input :winemaker_profile, label: 'jeune vigneron ou installé'%>
        <%= f.input :deferred_remuneration, label: 'différe de rendement ?' %>
        <%= f.input :date_of_end, label: 'date de fin d\'investissement' %>
        <%= f.button :submit, "Valider", class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/investments/destroy.html.erb
<h1>Investments#destroy</h1>
<p>Find me in app/views/investments/destroy.html.erb</p>

app/views/investments/edit.html.erb
<h1>Investments#edit</h1>
<p>Find me in app/views/investments/edit.html.erb</p>

app/views/investments/index.html.erb
<div class="banner-investment"></div>
<div class="container-investment">
<body class="body-investment">
  <div class="title-page">
    Investissements disponibles
  </div>
             <div id=filter>
                <%= simple_form_for @group, url: investments_path, method: :get, remote: true, html: {class: 'form-inline'} do |f| %>
              <br>
              <% regions = ["Bordeaux", "Bourgogne", "Alsace", "Beaujolais", "Alsace", "Champagne", "Corse", "Jura", "Languedoc-Roussillon", "Provence", "Savoie", "Sud-Ouest", "Vallée de la Loire", "Vallée du Rhône"] %>
              <%= f.input :region, as: :select, label: 'Région viticole', collection: regions %>
              <%= f.input :ticket_amount, label: "Montant du ticket d'entrée" %>
              <%= f.input :winemaker_profile, as: :select, label: 'Profil du Vigneron', collection: ["Jeune vigneron", "Vigneron installé"] %>
              <hr>
            <% end %>
           </div>

        <div class="container-cards">
          <%= render 'cards_results', investments: @investments %>
        </div>
</div>

app/views/investments/index.js.erb
document.querySelector('.container-cards').innerHTML = '<%= j render 'cards_results', investments: @investments %>';
fillGlasses()

app/views/investments/new.html.erb
<h1 class='title-page text-center' >Publier un nouvel investissement</h1>
<br>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <%= simple_form_for @investment do |f| %>
        <%= f.input :investment_name, label: 'Nom investissemernt' %>
        <%= f.input :punchline, label: 'puncline de l\'invest' %>

        <p>Exploitation</p>
        <hr>
        <%= f.input :winemaker_name, label: 'your name' %>
        <%= f.input :domaine_name, label: 'nom de votre deomaine' %>
        <%= f.input :designation, label: 'Appelation' %>
        <%= f.input :region, label: 'region' %>
        <%= f.input :description, label: 'votre description'%>
        <%= f.input :bio, label: 'Bio : oui / non', collection: ["Oui","Non"] %>
        <p>Vigneron</p>
        <hr>
        <%= f.input :winemaker_profile, label: 'jeune vigneron ou installé', collection: ["Jeune vigneron","Installation existante"] %>
        <p>Financier</p>
        <hr>
        <%= f.input :ticket_amount, label: 'Montant du ticket' %>
        <%= f.input :investment_total,label: 'Montant du ticket' %>
        <%= f.input :share_available, label: 'Parts disponibles'%>
        <%= f.input :total_share, label: 'parts totales'  %>
        <%= f.input :profitability, label: '% rendement' %>
        <%= f.input :remuneration, label: 'nbr de bouteilles pour une part' %>
        <%= f.input :deferred_remuneration, label: 'différe de rendement ?', collection: ["Oui","Non"] %>
        <%= f.input :date_of_end, label: 'date de fin d\'investissement', as: :date %>
        <%= f.button :submit, "Valider", class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/investments/show.html.erb
<div class="banner-investment"></div>
<!--  CONTENT -->
<br>
<br>
<body class="body-investment">

<div class="col-md-12 text-center">
  <h1> <strong> <%= @investment.investment_name %> </strong></h1>
  <h5 class="pb-3 pt-2"><%= @investment.punchline %></h5>
  <span class="BPDUh"></span>
  <br>
</div>
<div class="container">
  <div class="row investment-title">
    <div class="col-8">
      <%= cl_image_tag @investment.photo.key, crop: :fill, class: "image-invests" if @investment.photo.attached? %>
    </div>
    <div class="col-xs-12 col-md-4">
      <div class="right-element">
        <div class="day-left">
        </div>
      </div>
      <div class="card card-product text-center p-3 card-red">
        <div class="card-description product">
          <div class="icon text-center pb-3 pt-3">
            <%= image_tag(@investment.user.avatar, class: "avatar-large-invest w-2", alt: "avatar-large")  %>
          </div>
          <div>
            <div class="align-self-center ml-3"><h4><strong><%= @investment.user.first_name %> <%= @investment.user.last_name %></strong></h4></div>
          </div>
        </div>
        <hr>
        <div class="card-description product">
          <div class="icon text-center">
            <%= image_tag("wine1.png", class: "image-domaine") %>
          </div>
          <div>
            <h4 class="pt-3"><%= @investment.designation %></h4>
            <p class="mb-0"> <%= @investment.region  %> </p>
          </div>
        </div>
        <hr>
        <div class="card-description product">
          <div class="icon text-center pb-0">
            <%= image_tag("startup.png", class: "image-project") %>
          </div>
          <div>
            <h2 class="title-invstment pt-2"><strong><%= number_to_currency(@investment.investment_total, precision: 0, :unit => " €  ") %></strong></h2>
            <div>
              <small>A partir de</small>
              <h5 class="title-invstment"> € <strong> <%= @investment.ticket_amount %></strong><small> / ticket</h5></small>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

<div class="exp-show ">
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-8">
      <div class="left-element">
        <div class="align-items-center">
          <h2> <strong><%= @investment.domaine_name %></strong> </h2>
          <div id="prod"class="key groupe-progress">
            <div> <p><%= @investment.description  %> </p> </div>
              <hr>

          <div class="d-flex">
            <div>
              <p class="ml-3"><%= image_tag("wine.png", class: "image-wine") %><%= image_tag("wine.png", class: "image-wine") %><%= image_tag("wine.png", class: "image-wine") %></p>
              <p class="ml-3"><%= image_tag("plant.png", class: "image-money") %></p>
              <p class="ml-3"> <%= image_tag("money2.png", class: "image-money") %></p>
            </div>

            <div >
              <p class="ml-4 pb-2 pt-2"> <small><strong>Bouteilles/an: </strong></small> </p>
              <p class="mr-3 ml-4 pb-3 pt-3"> <small><strong>Rendement: </strong></small></p>
              <p class="mr-3 ml-4 pb-3 pt-3"> <small><strong>Vigneron: </strong></small></p>

            </div>

            <div class="pr-2">
              <p class='pb-2 pt-2 pl-4'> <%= @investment.remuneration %></p>
              <p class='pb-3 pt-3 pl-4'><%= @investment.profitability  %> %</p>
              <p class='pb-3 pt-3 pl-4'><%= @investment.winemaker_profile %></p>
            </div>
              <p class="pl-4"><% if @investment.bio == true %>
                    <%= image_tag "https://nibuniconnu.fr/wp-content/uploads/2018/08/mise-avant.png", class:"wine-bio" %>
                  <% else  %>
                    <%= ""%>
                  <% end  %></p>
            <div>
            </div>
          </div>


          </div>
        </div>
        <br>

        <h3 class="mb-2"><strong>Groupes intéressés</strong></h3>

        <div class="exp-desc groupe-progress ">
          <%= render 'show_groups', investment: @investment %>
        </div>
      </div>
    </div>


    <div class="col-xs-12 col-md-4">

      <div class="right-element">
        <div class="day-left"></div>
        <h3 class="text-center pb-3 pb-2"> <strong>Evénements</strong> </h3>
      </div>

      <% @investment.offered_services.each do |offer| %>
      <div class="card card-product text-center card-red">
        <div class="card-description product">
          <div class="icon text-center pt-2"> <%= image_tag("ticket.png", class: "image-ticket") %></div>
          <span style="color:#a23e48"><strong> <%= offer.title %></strong> </span>
          <hr class="product">
          <p class="ticket-number p-2" style="color:#a23e48"><%= offer.description %></p>
        </div>
      </div>
      <br>
      <% end %>
    </div>


  </div>
</div>

</body>

app/views/investments/update.html.erb
<h1>Investments#update</h1>
<p>Find me in app/views/investments/update.html.erb</p>