config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'

  resources :investments, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :offered_services, only: [:index, :show, :new, :create]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :groups, only: [:show, :new, :create, :edit, :update, :destroy] do
    member do
      post "set_favori/:investment_id", to: 'groups#set_favori', as: :set_favori
    end
    resources :users_groups, only: [:index, :show] do
      collection do
        post :join_request
        post :invite
      end
    end
  end

  resources :users_groups, only: [] do
    member do
      patch :confirm
    end
  end

end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :admin, foreign_key: :user_id, class_name: "User"
  has_many :users_groups
  has_many :users, through: :users_groups

  belongs_to :investment, optional: true

  SERVICES = ["Découverte des vendanges",
    "Etiquette de bouteille personnalisée",
    "Invitation à la dégustation annuelle",
    "Visite du domaine",
    "Initiation au processus de vinification"]

  before_validation :clean_empty_services

  validates :name, presence: true , uniqueness: true
  validates :region, inclusion: { in: ["Alsace", "Beaujolais", "Bordeaux", "Bourgogne", "Champagne", "Corse", "Jura", "Languedoc-Roussillon", "Provence", "Savoie", "Sud-Ouest", "Vallée de la Loire", "Vallée du Rhône"] }, allow_nil: true
  validates :winemaker_profile, inclusion: { in: ["Jeune vigneron", "Vigneron installé"] }, allow_nil: true
  validate :services_inclusion

  def image_url
    "https://dwj199mwkel52.cloudfront.net/assets/lewagon-logo-square-fe76916e1b923ade71e253ae6dc031d936e5e8eebac4e26b0fbac650ea6ee360.png"
  end

  def members
    users.where.not(users_groups: {status: 'pending'}).to_a << admin
  end

  def ready?
    members.size == investment.total_share
  end

  private

  def clean_empty_services
    services.reject! { |x| x.blank? } if services
  end

  def services_inclusion
    return if services.blank?

    services.each do |service|
      errors.add(:services, "'#{service}' not include in authorized services") unless service.in?(SERVICES)
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def show
    @group = Group.find(params[:id])
    @investments = InvestmentsByGroup.call(@group)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.admin = current_user
    if @group.save!
      redirect_to group_path(@group)
    else
      render 'new'
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    @group.admin = current_user
    if @group.update!(group_params)
      redirect_to group_path(@group)
    else
      render 'new'
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    redirect_to groups_path
  end

  def set_favori
    @group = Group.find(params[:id])
    @investment = Investment.find(params[:investment_id])
    @group.update!(investment: @investment)
    @investments = InvestmentsByGroup.call(@group)
  end

  private

  def group_params
    params.require(:group).permit(
      :name,
      :status,
      :region,
      :designation,
      :ticket_amount,
      :share_available,
      :investment_total,
      :winemaker_profile,
      :deferred_remuneration,
      :investment_id,
      :votes,
      :profitability,
      services: []
    )
  end
end

app/views/groups/_cards_top.html.erb
<% favori_set = @group.investment.present? %>

<div id="group-id" data-group-id = <%= @group.id %>>
  <% @investments[0..5].each do |investment| %>

    <% if @group.investment.nil? %>
      <% color = "" %>
    <% elsif @group.investment == investment %>

      <% color = "#E9D2D5" %>
      <% border = "solid" %>
      <% bordercolor = "#a43d46" %>

    <% else %>
      <% color = "" %>
      <% opacity = "0.5" %>
    <% end %>

    <div class="card-top" data-investment-id="<%= investment.id %>" style="background-color: <%= color %>;border: <%= border %>; opacity: <%= opacity %>; border-color: <%= bordercolor %>">
      <div class="image">
        <%= cl_image_tag investment.photo.key, height: 200, width: 300, crop: :fill if investment.photo.attached? %>
        <h2><%=investment.domaine_name %></h2>
        <p><%= investment.region %> - <%= investment.designation %></p>
      </div>
      <div>
      <div class= "card-top-infos">
        <div class="card-top-text d-flex align-content-around flex-wrap">
            <h3>Ticket d'entrée :</h3><h3 class= "green-top"><%= investment.ticket_amount %> €</h3>
            <h3>Nombre de parts :</h3><h3 class= "green-top"><%= investment.total_share %></h3>
            <h3>Montant invest :</h3><h3 class= "green-top"><%= investment.investment_total %> €</h3>
        </div>
          <div class="card-top-glass">
            <svg viewBox="0 0 161 301" style="height: 100px" data-size="<%= investment.match / 100.0 %>">
              <clipPath id="wine-clippath">
              <path d="M80.125,138.75c-5.973,0 -12.822,-1.152 -19.834,-3.387l-0.166,-0.053c-6.667,-2.123 -13.482,-5.221 -19.849,-9.235l-0.151,-0.095c-16.52,-10.43 -30,-26.96 -30,-48.48c0,-12.61 7.5,-38.75 16.47,-56.25l106.64,0c9.01,17.75 16.89,43.64 16.89,56.25c0,38.585 -44.017,61.162 -69.848,61.25l-0.152,0Z" fill="#000"></path>
              </clipPath>
              <image xlink:href="https://s3-us-west-2.amazonaws.com/s.cdpn.io/395186/wine.svg" x="0" y="0" width="100%" height="100%"></image>
              <g class="glass-fill" clip-path="url(#wine-clippath)">
                <rect x="10" y="20" width="31" height="120" style="fill: #874640;"></rect>
                <rect x="40" y="20" width="21" height="120" style="fill: #AA6F65;"></rect>
                <rect x="60" y="20" width="21" height="120" style="fill: #874640;"></rect>
                <rect x="80" y="20" width="70" height="120" style="fill: #751D19;"></rect>
              </g>
            </svg>
            <h3 class="scoring-match"><%= investment.match %> %</h3>
          </div>
        </div>
        <div class="card-top-buttons">
          <%= link_to "Plus d'info", investment_path(investment), class: 'btn-top-green' %>
          <%= link_to "Investir", set_favori_group_path(@group, investment), method: :post, remote: true, class: 'btn-top-red' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/groups/edit.html.erb
<h1 class='title-page'>Modifier votre projet d'investissement</h1>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <%= simple_form_for @group do |f| %>
        <%= f.input :name, label: 'Nom du groupe' %>
        <%= f.input :region, label: 'Région(s) viticole(s) souhaitée(s)', collection: ["Alsace", "Beaujolais", "Bordeaux", "Bourgogne", "Champagne", "Corse", "Jura", "Languedoc-Roussillon", "Provence", "Savoie", "Sud-Ouest", "Vallée de la Loire", "Vallée du Rhône"] %>
        <%= f.input :designation, label: 'Appellation(s) souhaitée(s)' %>
        <%= f.input :ticket_amount, label: "Ticket d'entrée" %>
        <%= f.input :investment_total, label: "Montant de l'investissement total" %>
        <%= f.input :services, label: 'Services proposés par le vigneron', collection: ["Découverte des vendanges", "Etiquette de bouteille personnalisée", "Invitation à la dégustation annuelle", "Visite du domaine", "Initiation au processus de vinification"], input_html: { multiple: true } %>
        <%= f.input :winemaker_profile, label: 'Profil du vigneron', collection: ["Jeune vigneron", "Vigneron installé"], include_blank: false %>
        <%= f.button :submit, "Valider", class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class="container justify-content-center">


  <br><br><br>

  <br>

  <div class="row justify-content-center">

    <div class="col-xs-12 col-sm- col-sm-offset-3">
      <div>
        <%= simple_form_for @group, html: { id: "new_group_form"} do |f| %>
        <% categories = ["Découverte des vendanges", "Etiquette de bouteille personnalisée", "Invitation à la dégustation annuelle", "Visite du domaine", "Initiation au processus de vinification"]%>
        <% vigneron_profil = ["Jeune vigneron", "Vigneron installé"] %>

        <div class="row">
          <div class="col">
            <h2><strong>Créez votre groupe</strong></h2>
             <br>
            <br>
            <p style="color:#a23e48"><strong>Nom du groupe</strong></p>
            <%= f.input :name, placeholder:'', label: false%>
          </div>

        </div>
          <br>
          <div class="row">
            <div class="col">
              <p style="color:#a23e48"><strong>Région viticole</strong></p>
              <%= f.input :region, input_html: { class: 'select2'}, collection: ["Alsace", "Beaujolais", "Bordeaux", "Bourgogne", "Champagne", "Corse", "Jura", "Languedoc-Roussillon", "Provence", "Savoie", "Sud-Ouest", "Vallée de la Loire", "Vallée du Rhône"], label: false %>
            </div>
            <div class="col">
              <p style="color:#a23e48"><strong>Appellation</strong></p>
              <%= f.input :designation, placeholder: 'Saint-Joseph, Condrieu..', label: false %>
            </div>
          </div>
            <hr>
            <div class="row">
              <div class="col">
                <p style="color:#a23e48"><strong>Ticket d'entrée</strong></p>
                <%= f.input :ticket_amount, placeholder: "Montant", label:false %>
              </div>
              <div class="col">
                <p style="color:#a23e48"><strong>Investissement total</strong></p>
                <%= f.input :investment_total, placeholder: "Montant", label:false %>
              </div>
            </div>
              <hr>
            <div class="row">
              <div class="col">
                <p style="color:#a23e48"><strong>Services proposés par le vigneron</strong></p>
                <div class="form-group">
                 <!--  <label class="control-label check_boxes optional"></label>
                  <input type="hidden" name="group[services][]" value=""> -->
                  <div class="category-choices">
                    <% categories.each do |category| %>
                    <input type="checkbox" value="<%= category %>" name="group[services][]" id="group_services_<%= category %>">
                    <label for="group_services_<%= category %>" class="category-choice">
                      <%= category %>
                    </label>
                    <br>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col">
                 <p style="color:#a23e48"><strong>Profil du vigneron</strong></p>
                <div class="form-group">
                 <!--  <label class="control-label check_boxes optional"></label>
                  <input type="hidden" name="group[services][]" value=""> -->
                  <div class="category-choices">
                    <% vigneron_profil.each do |vigneron| %>
                    <input type="radio" value="<%= vigneron %>" name="group[winemaker_profile]" id="group_winemaker_profile_<%= vigneron %>">
                    <label for="group_winemaker_profile_<%= vigneron %>" class="category-choice">
                      <%= vigneron %>
                    </label>
                    <br>
                    <% end %>
                  </div>
                </div>

                <!-- <p style="color:#a23e48"><strong>Profil</strong></p> -->
                <%#= f.input :winemaker_profile, label: 'Profil du vigneron', as: :check_boxes, collection: ["Jeune vigneron", "Vigneron installé"], label:false %>
              </div>
            </div>
              <br>
            <div class="row">
              <div class="col">
                <%= f.button :submit, "Valider", class: 'btn btn-invest-test btn-invest-first w-100' %>
                <% end %>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>

app/views/groups/set_favori.js.erb
var cardsTopElement = document.querySelector('.cards-top')
var html = "<%= j render 'cards_top', investments: @investments %>"

cardsTopElement.innerHTML = html
fillGlasses()

app/views/groups/show.html.erb
<div class="banner-investment"></div>
<body class="body-investment">
  <div class="title-page">
    <%= @group.name %>
  </div>

  <div class="container container-group">
    <div id="container-left">
      <div class="group-block">
        <h4 class="group-title">Votre projet d'investissement</h4>
        <div class="card-body">
          <p>Région : <strong><%= @group.region %></strong> </p>
          <p>Appellation : <strong><%= @group.designation %></strong> </p>
          <p>Ticket d'entrée : <strong><%= number_to_currency(@group.ticket_amount, precision: 0, :unit => "€", format: "%n %u") %></strong> </p>
          <p>Investissement total : <strong><%= number_to_currency(@group.investment_total, precision: 0, :unit => "€", format: "%n %u") %></strong> </p>
          <p>Services proposés par le vigneron :
          <% @group.services&.each do |service| %>
            <strong><%= service %>, </strong>
            <% end %>
          </p>
          <p>Profil du vigneron : <strong><%= @group.winemaker_profile %></strong> </p>
        </div>
      </div>
      <div class="group-block">
        <h4 class="group-title">Suggestion d'investissements</h4>
        <div class="cards-top">
          <%= render 'cards_top', investments: @investments %>
        </div>
      </div>
    </div>

    <div id="container-right">
      <div class="group-block">
        <table class="table table-bordered table-member mb-0">
          <h4 class="group-title mb-0">Membres du groupe</h4>
          <thead>
            <tr>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td style="text-align: center"><small class="text-muted"></small> <span aria-label="<%= @group.admin.first_name %> <%= @group.admin.last_name %>" data-balloon-pos="up"><%= image_tag @group.admin.avatar, class: "avatar-bordered", alt: "avatar-bordered" %> </span> </td>

              <td style="text-align: center; vertical-align: middle"><small class="text-muted"></small>ADMIN</td>
            </tr>
          <% @group.users_groups.each do |groupuser|  %>
            <tr>
              <td style="text-align: center"><small class="text-muted" ></small> <span aria-label="<%= groupuser.user.first_name %> <%= groupuser.user.last_name %>" data-balloon-pos="up"><%= image_tag groupuser.user.avatar, class: "avatar-bordered", alt: "avatar-bordered" %></strong> </td>

              <td style="text-align: center; vertical-align: middle"><small class="text-muted" ></small>
                <% if groupuser.status == "pending" %>
                 <%= link_to confirm_users_group_path(groupuser), method: :patch do  %>
                   <button class="btn btn-outline-danger w-100">Confirmer</button>
                <% end %>
                <% else %>
                <%= "Membre" %>
                <% end %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
      <div class="group-block">
        <h4 class="group-title">Inviter un investisseur</h4>
        <div class="form-group d-flex align-items-center">
          <% available_users = User.all.to_a %>
          <% available_users.reject! {|u| u.id == @group.user_id } %>
          <% available_users.reject! {|u| u.in? @group.users } %>
          <%= form_tag(invite_group_users_groups_path(@group), style: 'width: 100%; text-align: center; padding-top: 15px') do %>
            <%= select_tag "user_ids", options_from_collection_for_select(available_users, "id", "email"), multiple: true, class: 'form-control select2', style: "width: 100%;" %>
            <%= submit_tag "inviter", class: "btn-invest-first btn-invest-test mx-auto boutton" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</body>