config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'

  resources :investments, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :offered_services, only: [:index, :show, :new, :create]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :groups, only: [:show, :new, :create, :edit, :update, :destroy] do
    member do
      post "set_favori/:investment_id", to: 'groups#set_favori', as: :set_favori
    end
    resources :users_groups, only: [:index, :show] do
      collection do
        post :join_request
        post :invite
      end
    end
  end

  resources :users_groups, only: [] do
    member do
      patch :confirm
    end
  end

end

app/views/shared/_card_result2.html.erb
<div class="card-result2">
  <div class="card-header">
    <div class="image-carte">
      <%= cl_image_tag investment.photo.key, height: 200, width: 300, crop: :fill if investment.photo.attached? %>
    </div>
    <div class="infos-text">
      <div class="region-name">
        <%= investment.region %>
      </div>
      <div class="domaine-name">
        <%= investment.domaine_name %>
      </div>
      <div class="designation">
        <%= investment.designation %>
      </div>
      <div class="producteur">
        Chouchouté par <%= investment.user.first_name %> <%= investment.user.last_name %>
      </div>
      <hr>
      <div class="match_chiffre">
        <%= investment.match %> % de matching avec vos critètres
      </div>
    </div>
    <div class="matching">
      <svg viewBox="0 0 161 301" class="drinks" style="height: 100px" data-size="<%= investment.match / 100.0 %>">
      <clipPath id="wine-clippath">
      <path d="M80.125,138.75c-5.973,0 -12.822,-1.152 -19.834,-3.387l-0.166,-0.053c-6.667,-2.123 -13.482,-5.221 -19.849,-9.235l-0.151,-0.095c-16.52,-10.43 -30,-26.96 -30,-48.48c0,-12.61 7.5,-38.75 16.47,-56.25l106.64,0c9.01,17.75 16.89,43.64 16.89,56.25c0,38.585 -44.017,61.162 -69.848,61.25l-0.152,0Z" fill="#000"></path>
      </clipPath>
      <image xlink:href="https://s3-us-west-2.amazonaws.com/s.cdpn.io/395186/wine.svg" x="0" y="0" width="100%" height="100%"></image>
      <g class="glass-fill" clip-path="url(#wine-clippath)">
        <rect x="10" y="20" width="31" height="120" style="fill: #874640;"></rect>
        <rect x="40" y="20" width="21" height="120" style="fill: #AA6F65;"></rect>
        <rect x="60" y="20" width="21" height="120" style="fill: #874640;"></rect>
        <rect x="80" y="20" width="70" height="120" style="fill: #751D19;"></rect>
      </g>
        </svg>
    </div>
  </div>
  <div class="card-footer">
    <div class="price">
      <%= investment.ticket_amount %> €
    </div>
    <div class="nb-parts">
      <%= investment.share_available %> parts
    </div>
    <%= link_to "Plus d'info", investment_path(investment), class: "btn-bot-green" %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="left">
      <%= link_to "/", class: "navbar-brand" do %>
        <%= image_tag "logo.png" %>
      <%= link_to "Mon vignoble", new_user_session_path, class: "nav-link" %>
      <% end %>
  </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to("Mon Groupe", group_path(current_user.my_group.id), class: "nav-link") if current_user.my_group %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag current_user.avatar, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <div class="right">
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
           <%= link_to "Espace Vignerons", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </div>
    </ul>
  </div>
</div>